# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updatewCpp <- function(W, P, Q, XtX, nzeroes, a) {
    invisible(.Call(`_CCregPCA_updatewCpp`, W, P, Q, XtX, nzeroes, a))
}

pcaccregCpp <- function(X, Q, nzeroes, itr, Wstart, nStarts, tol, printLoss) {
    .Call(`_CCregPCA_pcaccregCpp`, X, Q, nzeroes, itr, Wstart, nStarts, tol, printLoss)
}

rcpparma_hello_world <- function() {
    .Call(`_CCregPCA_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_CCregPCA_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_CCregPCA_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_CCregPCA_rcpparma_bothproducts`, x)
}

